export const COLLECTIONS = {
  ACCOUNT: 'ACCOUNT',
  CARD: 'CARD',
  CREDIT: 'CREDIT',
  EVENT: 'EVENT',
  EVENT_BANNER: 'EVENT_BANNER',
  FAQ: 'FAQ',
  TERMS: 'TERMS',
  PIGGYBANK: 'PIGGYBANK',
  TRANSACTION: 'TRANSACTION',
}
